import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase, ref, set, get, update, onValue, onDisconnect } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import { firebaseConfig, isFirebaseConfigured } from "./firebase-config.js";

const $=(id)=>document.getElementById(id);
function injectUI(){
  const style=document.createElement("style");style.textContent=`
  .pv-vote{text-align:center;border-color:#57482d;background:radial-gradient(650px 260px at 50% 0%,rgba(239,179,76,.14),transparent 65%),#111620}.pv-vote-icon{font-size:58px}.pv-vote-title{font-size:clamp(32px,10vw,50px);font-weight:950;letter-spacing:-.04em;margin:8px 0}.pv-vote-help{color:#a7b1c1;font-size:13px;line-height:1.5}
  .pv-vote-targets{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:17px}.pv-vote-target{min-height:50px;border:1px solid #3d4659;background:#141b26;color:#dce3ed;border-radius:14px;padding:9px;font-size:12px;font-weight:850}.pv-vote-target.selected{border-color:#a87931;background:#2b2416;color:#f7d89d}.pv-vote-sent{margin-top:12px;padding:12px;border:1px solid #2a5542;background:#11251c;color:#b7edcf;border-radius:13px;font-size:12px;font-weight:900}
  .pv-result{margin-top:12px;padding:12px;border:1px solid #2e5a47;background:#11251c;color:#b9edcf;border-radius:14px;font-size:13px;line-height:1.5;font-weight:850}.pv-witch{display:flex;align-items:center;gap:9px;text-align:left;margin-top:13px;padding:10px 11px;border:1px solid #5a492d;background:#261f13;color:#f1d394;border-radius:13px;font-size:12px;font-weight:800}.pv-witch input{width:19px;height:19px;accent-color:#efb34c}.pv-morning{margin-top:12px;color:#efc77e;font-size:12px;font-weight:800;line-height:1.5}
  @media(max-width:430px){.pv-vote-targets{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  const target=$("targetSection");if(target&&!$("pvWitchRow"))target.insertAdjacentHTML("beforebegin",`<label id="pvWitchRow" class="pv-witch hidden"><input id="pvWitchSave" type="checkbox"><span id="pvWitchText">ใช้ยาช่วยเป้าหมายของหมาป่า</span></label>`);
  const submit=$("submitActionBtn")?.parentElement;if(submit&&!$("pvTurnResult"))submit.insertAdjacentHTML("beforebegin",`<div id="pvTurnResult" class="pv-result hidden"></div>`);
  const phase=$("phaseView");if(phase&&!$("pvMorning"))phase.insertAdjacentHTML("beforeend",`<div id="pvMorning" class="pv-morning hidden"></div>`);
  const game=$("gameView");if(game&&!$("pvVoteView"))game.insertAdjacentHTML("beforeend",`
    <section id="pvVoteView" class="card pv-vote hidden"><div class="pv-vote-icon">🗳️</div><div class="pv-vote-title">ถึงเวลาโหวต</div><div class="pv-vote-help">เลือกผู้เล่น 1 คน • คะแนนจะไม่แสดงจนกว่าทุกคนจะโหวตครบ</div><div id="pvVoteTargets" class="pv-vote-targets"></div><button id="pvSubmitVote" class="btn primary" style="width:100%;margin-top:12px" disabled>ส่งโหวต</button><div id="pvVoteSent" class="pv-vote-sent hidden">✓ ส่งโหวตแล้ว รอ Host ยืนยันผล</div></section>`);
}
injectUI();

let db=null,auth=null,uid="",room="",myName="",players={},privateState={},publicState={},selected=new Set(),lastPhase="",voteId="",voteChoice="",voteSent="";
const join=$("joinView"),game=$("gameView"),lobby=$("lobbyView"),roleView=$("roleView"),phaseView=$("phaseView"),turnView=$("turnView"),voteView=$("pvVoteView");
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function path(x=""){return`rooms/${room}${x?"/"+x:""}`}
function show(v){[lobby,roleView,phaseView,turnView,voteView].forEach(x=>x?.classList.add("hidden"));v?.classList.remove("hidden")}
function roleName(r){return r?.th&&r.th!==r.name?r.th:(r?.name||"")}
function factionMeta(role){const cat=role?.cat||"Neutral";if(cat==="Werewolves")return{key:"werewolves",icon:"🐺",label:"ฝ่ายหมาป่า",lore:"รู้จักฝูงของตัวเอง และทำ Action ตอนกลางคืน"};if(cat==="Villagers")return{key:"villagers",icon:"🛡️",label:"ฝ่ายชาวบ้าน",lore:"ช่วยหาหมาป่าและใช้ความสามารถพิเศษเพื่อปกป้องหมู่บ้าน"};if(cat==="Neutral")return{key:"neutral",icon:"🕯️",label:"Role กลาง",lore:"มีเงื่อนไขชนะของตัวเองหรือเป็น Role เฉพาะทาง"};return{key:"additional",icon:"✨",label:"Role เสริม",lore:"Role เสริมที่เพิ่มสีสันหรือ house rule ให้เกม"}}
function applyRoleTheme(role){const meta=factionMeta(role);const revealed=$("revealedRoleCard"),hidden=$("hiddenRoleCard"),turn=$("turnView");revealed&&(revealed.dataset.faction=meta.key);hidden&&(hidden.dataset.faction=meta.key);turn&&(turn.dataset.faction=meta.key);$("roleFactionBadge")&&($("roleFactionBadge").textContent=`${meta.icon} ${meta.label}`);$("roleCrest")&&($("roleCrest").textContent=meta.icon);$("roleLore")&&($("roleLore").textContent=meta.lore);return meta}
function connection(t){$("connectionStatus").textContent=t}
function renderPlayers(){const list=Object.entries(players||{}).sort((a,b)=>(a[1].joinedAt||0)-(b[1].joinedAt||0));$("playerList").innerHTML=list.map(([id,p])=>{const dead=p.alive===false,reason=p.eliminatedBy==="vote"?" • ถูกโหวตออก":dead?" • ถูกกำจัด":"";return`<div class="player"><span class="dot ${dead?"dead":p.connected===false?"off":""}"></span>${esc(p.name)}${id===uid?" (คุณ)":""}${p.isHost?" • 👑 Host":""}${esc(reason)}${dead?" • 🔒 ไม่เปิด Role":""}</div>`}).join("");const me=players?.[uid],dead=me?.alive===false;$("deadBanner").classList.toggle("hidden",!dead);if(dead)$("deadBanner").textContent="☠️ คุณถูกกำจัดแล้ว — Role จะไม่ถูกเปิดเผย และคุณไม่มี Action/สิทธิ์โหวตต่อ"}
function renderRole(){const r=privateState?.role;if(!r)return;applyRoleTheme(r);$("roleName").textContent=roleName(r);$("roleEnglish").textContent=r.th&&r.th!==r.name?r.name:r.cat||"";$("roleAbility").textContent=r.ability||r.action||"ทำความสามารถตามกติกา";const extras=[];if(privateState?.teammates?.length)extras.push(`เพื่อนที่คุณรู้จัก: ${privateState.teammates.map(x=>x.name).join(", ")}`);if(privateState?.loverName)extras.push(`คู่รัก: ${privateState.loverName}`);$("teamText").textContent=extras.join(" • ");$("teamText").classList.toggle("hidden",!extras.length)}
function renderMorning(){const p=publicState?.phase||{},el=$("pvMorning");let t="";if(p.state==="day"){const d=Array.isArray(p.morningDeaths)?p.morningDeaths:[];t=d.length?`เมื่อคืน ${d.join(" และ ")} ถูกกำจัด • ไม่มีการเปิดเผย Role`:"เมื่อคืนไม่มีใครถูกกำจัด"}else if(p.state==="vote-result"&&p.eliminatedName)t=`${p.eliminatedName} ถูกโหวตออก • ไม่มีการเปิดเผย Role`;else if(p.state==="gameover")t=`เกมจบ • ${p.winner||""} ชนะ`;el.textContent=t;el.classList.toggle("hidden",!t)}
function renderState(){renderPlayers();renderRole();renderMorning();const r=privateState?.role,t=privateState?.turn,me=players?.[uid],dead=me?.alive===false,p=publicState?.phase||{};if(!r){show(lobby);$("lobbyText").textContent="เข้าห้องแล้ว • รอ Host สุ่มแจก Role";return}if(dead){show(phaseView);$("phaseTitle").textContent=p.state==="gameover"?"เกมจบ":"คุณถูกกำจัดแล้ว";$("phaseSub").textContent=p.state==="gameover"?(p.winner||""):"ดูเกมต่อได้ แต่ไม่มี Action/โหวต • Role ไม่ถูกเปิดเผย";return}if(p.state==="gameover"){show(phaseView);$("phaseTitle").textContent="เกมจบ";$("phaseSub").textContent=`${p.winner||""} ชนะ`;return}if(p.state==="vote"){renderVote();show(voteView);return}if(t?.active){renderTurn(t);show(turnView);return}if(!t||t.state==="lobby"||["lobby","assigned"].includes(p.state)){show(roleView);return}show(phaseView);if(p.state==="day"||p.state==="vote-result"||t.state==="day"){ $("phaseTitle").textContent="ทุกคนลืมตา";$("phaseSub").textContent="ช่วงกลางวัน • รอ Host เริ่มโหวต"}else{$("phaseTitle").textContent="หลับตา";$("phaseSub").textContent=`Night ${p.night||t.night||1} • ฟังเสียงเรียก Role จากเครื่อง Host`}}
function renderTurn(t){if(lastPhase!==t.phaseId){lastPhase=t.phaseId;selected.clear();$("sentMessage").classList.add("hidden");$("submitActionBtn").classList.remove("hidden");$("pvWitchSave").checked=false}applyRoleTheme(t.role||privateState?.role);$("turnRole").textContent=roleName(t.role);$("turnAction").textContent=t.action||t.ability||"ทำความสามารถของคุณ";const b=t.behavior||{targetCount:1,optional:false,allowSelf:false,kind:"generic"};let count=Number(b.targetCount)||0;if(b.kind==="witch"&&t.resources?.witchKillUsed)count=0;const result=t.result||"";$("pvTurnResult").textContent=result;$("pvTurnResult").classList.toggle("hidden",!result);const save=b.kind==="witch"&&t.context?.wolfTarget&&!t.resources?.witchHealUsed;$("pvWitchRow").classList.toggle("hidden",!save);if(save)$("pvWitchText").textContent=`ใช้ยาช่วย ${t.context.wolfTargetName}`;if(count===0){$("targetSection").classList.add("hidden");$("submitActionBtn").textContent="เสร็จแล้ว";$("submitActionBtn").disabled=false}else{$("targetSection").classList.remove("hidden");$("targetTitle").textContent=count===2?"เลือกผู้เล่น 2 คน":b.kind==="witch"?"เลือกเป้าหมายยากำจัด (ถ้าต้องการ)":"เลือกผู้เล่น 1 คน";$("submitActionBtn").textContent="ยืนยัน";const ex=new Set(t.excludedTargets||[]),list=Object.entries(players).filter(([id,p])=>p.alive!==false&&(b.allowSelf||id!==uid)&&!ex.has(id));$("targetList").innerHTML=list.map(([id,p])=>`<button class="target ${selected.has(id)?"selected":""}" data-pvt="${id}" type="button">${esc(p.name)}${id===uid?" (คุณ)":""}</button>`).join("");document.querySelectorAll("[data-pvt]").forEach(x=>x.onclick=()=>{const id=x.dataset.pvt;if(selected.has(id))selected.delete(id);else{if(selected.size>=count)selected.delete([...selected][0]);selected.add(id)}renderTurn(t)});const saveOnly=b.kind==="witch"&&$("pvWitchSave").checked;$("submitActionBtn").disabled=b.optional?!(selected.size===count||saveOnly):selected.size!==count}$("skipActionBtn").classList.toggle("hidden",!b.optional)}
async function action(skip=false){const t=privateState?.turn;if(!t?.phaseId)return;await set(ref(db,path(`actions/${t.night}/${t.phaseId}/${uid}`)),{selected:skip?[]:[...selected],skipped:skip,saveWolfTarget:!skip&&t.behavior?.kind==="witch"?Boolean($("pvWitchSave").checked):false,submittedAt:Date.now()});$("sentMessage").textContent="✓ ส่ง Action แล้ว • รอฟังเสียงเรียกหลับตา";$("sentMessage").classList.remove("hidden");$("submitActionBtn").classList.add("hidden");$("skipActionBtn").classList.add("hidden")}
function renderVote(){const p=publicState?.phase||{},id=p.voteId||"";if(voteId!==id){voteId=id;voteChoice="";voteSent=""}const list=Object.entries(players).filter(([id,p])=>p.alive!==false&&id!==uid);$("pvVoteTargets").innerHTML=list.map(([id,p])=>`<button class="pv-vote-target ${voteChoice===id?"selected":""}" data-pvv="${id}" type="button">${esc(p.name)}${p.isHost?" 👑":""}</button>`).join("");document.querySelectorAll("[data-pvv]").forEach(x=>x.onclick=()=>{if(voteSent===voteId)return;voteChoice=x.dataset.pvv;renderVote()});const sent=voteSent===voteId;$("pvSubmitVote").disabled=!voteChoice||sent;$("pvSubmitVote").classList.toggle("hidden",sent);$("pvVoteSent").classList.toggle("hidden",!sent)}
async function submitVote(){if(!voteId||!voteChoice)return;await set(ref(db,path(`votes/${voteId}/${uid}`)),{target:voteChoice,submittedAt:Date.now()});voteSent=voteId;renderVote()}
async function joinRoom(){if(!db||!uid)return alert("ยังไม่ได้เชื่อม Firebase");const code=$("roomInput").value.trim().toUpperCase(),name=$("nameInput").value.trim();if(code.length!==5)return alert("Room Code ต้องมี 5 ตัว");if(!name)return alert("กรุณาใส่ชื่อ");if(!(await get(ref(db,`rooms/${code}/hostUid`))).exists())return alert("ไม่พบห้องนี้");room=code;myName=name;const pr=ref(db,path(`players/${uid}`)),old=await get(pr),u={name,connected:true};if(!old.exists())u.joinedAt=Date.now();await update(pr,u);try{await onDisconnect(ref(db,path(`players/${uid}/connected`))).set(false)}catch{}localStorage.setItem("ww_player_room",room);localStorage.setItem("ww_player_name",name);$("roomText").textContent=room;$("meText").textContent=name;join.classList.add("hidden");game.classList.remove("hidden");onValue(ref(db,path("public")),s=>{publicState=s.val()||{};renderState()});onValue(ref(db,path("players")),s=>{players=s.val()||{};renderState()});onValue(ref(db,path(`private/${uid}`)),s=>{privateState=s.val()||{};renderState()})}

$("joinBtn").onclick=joinRoom;$("roomInput").oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,5);$("revealBtn").onclick=()=>{$("hiddenRoleCard").classList.add("hidden");$("revealedRoleCard").classList.remove("hidden")};$("hideRoleBtn").onclick=()=>{$("revealedRoleCard").classList.add("hidden");$("hiddenRoleCard").classList.remove("hidden")};$("submitActionBtn").onclick=()=>action(false);$("skipActionBtn").onclick=()=>action(true);$("pvWitchSave").onchange=()=>privateState?.turn&&renderTurn(privateState.turn);$("pvSubmitVote").onclick=submitVote;

(async()=>{const q=new URLSearchParams(location.search);$("roomInput").value=(q.get("room")||localStorage.getItem("ww_player_room")||"").toUpperCase();$("nameInput").value=localStorage.getItem("ww_player_name")||"";if(!isFirebaseConfigured()){$("setupWarning").classList.remove("hidden");connection("ต้องตั้งค่า Firebase");$("joinBtn").disabled=true;return}try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);uid=(await signInAnonymously(auth)).user.uid;connection("ออนไลน์")}catch(e){console.error(e);connection("เชื่อมไม่สำเร็จ")}})();
